-- SINH TỰ ĐỘNG — KHÔNG SỬA TAY.
-- Nguồn: backend/app/semantic/feature_spec.py + backend/scripts/generate_dbt_models.py
-- Sinh lại:  cd backend && python -m scripts.generate_dbt_models
--
-- Bản nháp của feature.gsm_transaction. dbt test chạy TRÊN BẢNG NÀY, trước khi
-- publish_gold.py ghi sang feature.* — CHECK constraint của bảng gold sẽ từ chối
-- INSERT trước khi test kịp chạy nếu đặt test ở đó. 167 cột feature.
--
-- alias trùng tên bảng gold để `parity_check --source dbt_work` so thẳng candidate với
-- baseline mà không cần bảng ánh xạ tên. Schema thì vẫn là dbt_work — dbt không có
-- quyền DDL trên feature.*, việc ghi sang đó là của publish_gold.py.
{{ config(alias='gsm_transaction') }}

select
    s.customer_id,
    s.snapshot_date,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'canceled') as canceled_original_price_max_daily,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled') as canceled_original_price_max_l12m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled') as canceled_original_price_max_l1m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled') as canceled_original_price_max_l1w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled') as canceled_original_price_max_l2w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled') as canceled_original_price_max_l3m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled') as canceled_original_price_max_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_daily,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled'), 0) as canceled_original_price_sum_l6m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'canceled') as canceled_txn_active_day_count_daily,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled') as canceled_txn_active_day_count_l12m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled') as canceled_txn_active_day_count_l1m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled') as canceled_txn_active_day_count_l1w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled') as canceled_txn_active_day_count_l2w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled') as canceled_txn_active_day_count_l3m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled') as canceled_txn_active_day_count_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'canceled') as canceled_txn_count_daily,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled') as canceled_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled') as canceled_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled') as canceled_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled') as canceled_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled') as canceled_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled') as canceled_txn_count_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled' and t.is_weekday), 0) as canceled_weekday_original_price_sum_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'canceled' and t.is_weekday) as canceled_weekday_txn_count_l6m,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_daily,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l12m,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l1m,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l1w,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l2w,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l3m,
    coalesce(sum(t.discount_amount) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0) as completed_discount_amount_sum_l6m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as completed_original_price_max_daily,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as completed_original_price_max_l12m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as completed_original_price_max_l1m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as completed_original_price_max_l1w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as completed_original_price_max_l2w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as completed_original_price_max_l3m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as completed_original_price_max_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed'), 0) as completed_original_price_sum_daily,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0) as completed_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0) as completed_original_price_sum_l1m,
    case when (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0)) <> 0 then round(((coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0))::float8 / (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0))::float8) * 10000) / 10000 end as completed_original_price_sum_l1m_vs_l3m,
    case when (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0)) <> 0 then round(((coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0))::float8 / (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0))::float8) * 10000) / 10000 end as completed_original_price_sum_l1m_vs_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed'), 0) as completed_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed'), 0) as completed_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0) as completed_original_price_sum_l3m,
    case when (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0)) <> 0 then round(((coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0))::float8 / (coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0))::float8) * 10000) / 10000 end as completed_original_price_sum_l3m_vs_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0) as completed_original_price_sum_l6m,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_daily,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l12m,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l1m,
    case when (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0), 2)) <> 0 then round(((round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0), 2))::float8 / (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0), 2))::float8) * 10000) / 10000 end as completed_trip_distance_km_sum_l1m_vs_l3m,
    case when (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0), 2)) <> 0 then round(((round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0), 2))::float8 / (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0), 2))::float8) * 10000) / 10000 end as completed_trip_distance_km_sum_l1m_vs_l6m,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l1w,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l2w,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l3m,
    case when (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0), 2)) <> 0 then round(((round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0), 2))::float8 / (round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0), 2))::float8) * 10000) / 10000 end as completed_trip_distance_km_sum_l3m_vs_l12m,
    round(coalesce(sum(t.distance_km) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0), 2) as completed_trip_distance_km_sum_l6m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as completed_txn_active_day_count_daily,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as completed_txn_active_day_count_l12m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as completed_txn_active_day_count_l1m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as completed_txn_active_day_count_l1w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as completed_txn_active_day_count_l2w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as completed_txn_active_day_count_l3m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as completed_txn_active_day_count_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as completed_txn_count_daily,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as completed_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as completed_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as completed_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as completed_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as completed_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as completed_txn_count_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_weekday), 0) as completed_weekday_original_price_sum_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_weekday) as completed_weekday_txn_count_l6m,
    (s.snapshot_date - min(t.trip_date)) as days_since_first_txn_l12m,
    (s.snapshot_date - max(t.trip_date)) as days_since_last_txn_l12m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as finished_original_price_max_daily,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as finished_original_price_max_l12m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as finished_original_price_max_l1m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as finished_original_price_max_l1w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as finished_original_price_max_l2w,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as finished_original_price_max_l3m,
    max(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as finished_original_price_max_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed'), 0) as finished_original_price_sum_daily,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'), 0) as finished_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'), 0) as finished_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed'), 0) as finished_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed'), 0) as finished_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'), 0) as finished_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'), 0) as finished_original_price_sum_l6m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_daily,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_daytime), 0) as finished_time_daytime_original_price_sum_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_daily,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_daytime) as finished_time_daytime_txn_count_l6m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as finished_txn_active_day_count_daily,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as finished_txn_active_day_count_l12m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as finished_txn_active_day_count_l1m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as finished_txn_active_day_count_l1w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as finished_txn_active_day_count_l2w,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as finished_txn_active_day_count_l3m,
    count(distinct t.trip_date) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as finished_txn_active_day_count_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 0 and t.status_group = 'completed') as finished_txn_count_daily,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed') as finished_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed') as finished_txn_count_l1m,
    case when (count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed')) <> 0 then round(((count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'))::float8 / (count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'))::float8) * 10000) / 10000 end as finished_txn_count_l1m_vs_l3m,
    case when (count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed')) <> 0 then round(((count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed'))::float8 / (count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed'))::float8) * 10000) / 10000 end as finished_txn_count_l1m_vs_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed') as finished_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed') as finished_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed') as finished_txn_count_l3m,
    case when (count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed')) <> 0 then round(((count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed'))::float8 / (count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed'))::float8) * 10000) / 10000 end as finished_txn_count_l3m_vs_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed') as finished_txn_count_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.service_type = 'bike') as finished_type_bike_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.service_type = 'bike') as finished_type_bike_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.service_type = 'express') as finished_type_express_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.service_type = 'express') as finished_type_express_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.service_type = 'food') as finished_type_food_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.service_type = 'food') as finished_type_food_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.service_type = 'taxi') as finished_type_taxi_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.service_type = 'taxi') as finished_type_taxi_txn_count_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l12m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l1m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l1w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l2w,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l3m,
    coalesce(sum(t.total_fare) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_weekday), 0) as finished_weekday_original_price_sum_l6m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 364 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l12m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 29 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l1m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 6 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l1w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 13 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l2w,
    count(*) filter (where t.trip_date >= s.snapshot_date - 89 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l3m,
    count(*) filter (where t.trip_date >= s.snapshot_date - 179 and t.status_group = 'completed' and t.is_weekday) as finished_weekday_txn_count_l6m
from {{ ref('silver_customer_snapshot') }} s
left join {{ ref('silver_gsm_trip') }} t
       on t.customer_id = s.customer_id
      and t.trip_date <= s.snapshot_date
group by s.customer_id, s.snapshot_date
