-- SINH TỰ ĐỘNG — KHÔNG SỬA TAY.
-- Nguồn: backend/app/semantic/feature_spec.py + backend/scripts/generate_dbt_models.py
-- Sinh lại:  cd backend && python -m scripts.generate_dbt_models
--
-- Bản nháp của feature.vinfast_transaction. Ba CTE vì ba nguồn có GRAIN KHÁC
-- NHAU: đơn hàng, đơn mua xe, bản ghi bàn giao. Join chung một lượt thì nhân dòng.
-- 186 cột đơn hàng + 7 cột người mua + 9 cột sở hữu.
--
-- alias trùng tên bảng gold để `parity_check --source dbt_work` so thẳng candidate với
-- baseline mà không cần bảng ánh xạ tên. Schema thì vẫn là dbt_work — dbt không có
-- quyền DDL trên feature.*, việc ghi sang đó là của publish_gold.py.
{{ config(alias='vinfast_transaction') }}

with don_hang as (
  select
    s.customer_id,
    s.snapshot_date,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_daily,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l12m,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l1m,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l1w,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l2w,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l3m,
    (s.snapshot_date - min(o.updated_date) filter (where o.status = 'completed')) as days_since_first_completed_txn_days_l6m,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_daily,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l12m,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l1m,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l1w,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l2w,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l3m,
    (s.snapshot_date - max(o.updated_date) filter (where o.status = 'completed')) as days_since_last_completed_txn_days_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_amount_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_amount_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_amount_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_amount_sum_l3m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_canceled_count_l1m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_canceled_count_l1m_vs_l3m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_canceled_count_l1m_vs_l6m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_canceled_count_l3m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_price_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_price_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_price_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_canceled_price_sum_l3m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_amount_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_amount_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_amount_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_amount_sum_l3m_vs_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories') as txn_accessories_completed_count_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_completed_count_l1m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_completed_count_l1m_vs_l3m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_completed_count_l1m_vs_l6m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'))::float8) * 10000) / 10000 end as txn_accessories_completed_count_l3m_vs_l12m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0) as txn_accessories_completed_price_sum_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_price_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_price_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_price_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories'), 0))::float8) * 10000) / 10000 end as txn_accessories_completed_price_sum_l3m_vs_l12m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled') as txn_canceled_active_day_count_daily,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled') as txn_canceled_active_day_count_l12m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled') as txn_canceled_active_day_count_l1m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled') as txn_canceled_active_day_count_l1w,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled') as txn_canceled_active_day_count_l2w,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled') as txn_canceled_active_day_count_l3m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled') as txn_canceled_active_day_count_l6m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_daily,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l12m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l1m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l1w,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l2w,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l3m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled'), 0) as txn_canceled_amount_sum_l6m,
    count(*) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled') as txn_canceled_count_daily,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled') as txn_canceled_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled') as txn_canceled_count_l1m,
    count(*) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled') as txn_canceled_count_l1w,
    count(*) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled') as txn_canceled_count_l2w,
    count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled') as txn_canceled_count_l3m,
    count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled') as txn_canceled_count_l6m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_daily,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l12m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l1m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l1w,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l2w,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l3m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled'), 0) as txn_canceled_price_sum_l6m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled') as txn_canceled_processing_time_max_daily,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled') as txn_canceled_processing_time_max_l12m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled') as txn_canceled_processing_time_max_l1m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled') as txn_canceled_processing_time_max_l1w,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled') as txn_canceled_processing_time_max_l2w,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled') as txn_canceled_processing_time_max_l3m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled') as txn_canceled_processing_time_max_l6m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled') as txn_canceled_processing_time_min_daily,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled') as txn_canceled_processing_time_min_l12m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled') as txn_canceled_processing_time_min_l1m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled') as txn_canceled_processing_time_min_l1w,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled') as txn_canceled_processing_time_min_l2w,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled') as txn_canceled_processing_time_min_l3m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled') as txn_canceled_processing_time_min_l6m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_completed_active_day_count_daily,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_completed_active_day_count_l12m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_completed_active_day_count_l1m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_completed_active_day_count_l1w,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_completed_active_day_count_l2w,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_completed_active_day_count_l3m,
    count(distinct o.created_date) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_completed_active_day_count_l6m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed'), 0) as txn_completed_amount_sum_daily,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed'), 0) as txn_completed_amount_sum_l12m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed'), 0) as txn_completed_amount_sum_l1m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed'), 0) as txn_completed_amount_sum_l1w,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed'), 0) as txn_completed_amount_sum_l2w,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed'), 0) as txn_completed_amount_sum_l3m,
    coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed'), 0) as txn_completed_amount_sum_l6m,
    round(sum(o.battery_kwh) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed'), 2) as txn_completed_battery_sum_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_completed_count_daily,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_completed_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_completed_count_l1m,
    count(*) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_completed_count_l1w,
    count(*) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_completed_count_l2w,
    count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_completed_count_l3m,
    count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_completed_count_l6m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed'), 0) as txn_completed_price_sum_daily,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed'), 0) as txn_completed_price_sum_l12m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed'), 0) as txn_completed_price_sum_l1m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed'), 0) as txn_completed_price_sum_l1w,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed'), 0) as txn_completed_price_sum_l2w,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed'), 0) as txn_completed_price_sum_l3m,
    coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed'), 0) as txn_completed_price_sum_l6m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_completed_processing_time_max_daily,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_completed_processing_time_max_l12m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_completed_processing_time_max_l1m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_completed_processing_time_max_l1w,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_completed_processing_time_max_l2w,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_completed_processing_time_max_l3m,
    max(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_completed_processing_time_max_l6m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_completed_processing_time_min_daily,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_completed_processing_time_min_l12m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_completed_processing_time_min_l1m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_completed_processing_time_min_l1w,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_completed_processing_time_min_l2w,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_completed_processing_time_min_l3m,
    min(o.processing_minutes) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_completed_processing_time_min_l6m,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'accessories' and o.has_discount) as txn_discount_accessories_completed_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_daily,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l1m,
    count(*) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l1w,
    count(*) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l2w,
    count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l3m,
    count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.has_discount) as txn_discount_canceled_count_l6m,
    count(*) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_daily,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l1m,
    count(*) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l1w,
    count(*) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l2w,
    count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l3m,
    count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.has_discount) as txn_discount_completed_count_l6m,
    count(*) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_daily,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l12m,
    count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l1m,
    count(*) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l1w,
    count(*) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l2w,
    count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l3m,
    count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'delivered' and o.has_discount) as txn_discount_delivered_count_l6m,
    count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'nvso' and o.has_discount) as txn_discount_nvso_completed_count_l12m,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_first_completed_updated_date_min_daily,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_first_completed_updated_date_min_l12m,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_first_completed_updated_date_min_l1m,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_first_completed_updated_date_min_l1w,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_first_completed_updated_date_min_l2w,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_first_completed_updated_date_min_l3m,
    min(o.updated_date) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_first_completed_updated_date_min_l6m,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 0 and o.status = 'completed') as txn_last_completed_updated_date_max_daily,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed') as txn_last_completed_updated_date_max_l12m,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed') as txn_last_completed_updated_date_max_l1m,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 6 and o.status = 'completed') as txn_last_completed_updated_date_max_l1w,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 13 and o.status = 'completed') as txn_last_completed_updated_date_max_l2w,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed') as txn_last_completed_updated_date_max_l3m,
    max(o.updated_date) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed') as txn_last_completed_updated_date_max_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_amount_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_amount_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_amount_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_amount_sum_l3m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_canceled_count_l1m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_canceled_count_l1m_vs_l3m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_canceled_count_l1m_vs_l6m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_canceled_count_l3m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_price_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_price_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_price_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'cancelled' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_canceled_price_sum_l3m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_amount_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_amount_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_amount_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.paid_amount) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_amount_sum_l3m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_completed_count_l1m_vs_l12m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_completed_count_l1m_vs_l3m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_completed_count_l1m_vs_l6m,
    case when (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order')) <> 0 then round(((count(*) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'))::float8 / (count(*) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'))::float8) * 10000) / 10000 end as txn_wo_completed_count_l3m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_price_sum_l1m_vs_l12m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_price_sum_l1m_vs_l3m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 29 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 179 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_price_sum_l1m_vs_l6m,
    case when (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0)) <> 0 then round(((coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 89 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8 / (coalesce(sum(o.list_price) filter (where o.created_date >= s.snapshot_date - 364 and o.status = 'completed' and o.order_type = 'work_order'), 0))::float8) * 10000) / 10000 end as txn_wo_completed_price_sum_l3m_vs_l12m
  from {{ ref('silver_customer_snapshot') }} s
  left join {{ ref('silver_vinfast_order_state') }} o
         on o.customer_id = s.customer_id
        and o.snapshot_date = s.snapshot_date
  group by s.customer_id, s.snapshot_date
),

nguoi_mua as (
  select
    s.customer_id,
    s.snapshot_date,
    min(p.completed_date) as first_vehicle_purchase_date,
    coalesce(bool_or(p.order_id is not null), false) as is_vehicle_buyer,
    count(*) filter (where p.order_id is not null and true) as vehicle_purchase_completed_count_all,
    count(*) filter (where p.order_id is not null and p.completed_date >= s.snapshot_date - 364) as vehicle_purchase_completed_count_l12m,
    count(*) filter (where p.order_id is not null and p.completed_date >= s.snapshot_date - 29) as vehicle_purchase_completed_count_l1m,
    count(*) filter (where p.order_id is not null and p.completed_date >= s.snapshot_date - 89) as vehicle_purchase_completed_count_l3m,
    count(*) filter (where p.order_id is not null and p.completed_date >= s.snapshot_date - 179) as vehicle_purchase_completed_count_l6m
  from {{ ref('silver_customer_snapshot') }} s
  left join {{ ref('silver_vehicle_purchase') }} p
         on p.customer_id = s.customer_id
        and p.snapshot_date = s.snapshot_date
  group by s.customer_id, s.snapshot_date
),

so_huu as (
  select
    s.customer_id,
    s.snapshot_date,
    (s.snapshot_date - max(h.handed_over_date) filter (where h.is_handed_over)) as days_since_last_vehicle_handover,
    min(h.handed_over_date) filter (where h.is_handed_over) as first_vehicle_handover_date,
    coalesce(bool_or(h.is_pending), false) as is_vehicle_handover_scheduled,
    coalesce(bool_or(h.is_owned), false) as is_vehicle_owner,
    count(distinct h.vehicle_id) filter (where h.is_handed_over and true) as vehicle_delivered_count_all,
    count(distinct h.vehicle_id) filter (where h.is_handed_over and h.handed_over_date >= s.snapshot_date - 364) as vehicle_delivered_count_l12m,
    count(distinct h.vehicle_id) filter (where h.is_handed_over and h.handed_over_date >= s.snapshot_date - 29) as vehicle_delivered_count_l1m,
    count(distinct h.vehicle_id) filter (where h.is_handed_over and h.handed_over_date >= s.snapshot_date - 89) as vehicle_delivered_count_l3m,
    count(distinct h.vehicle_id) filter (where h.is_handed_over and h.handed_over_date >= s.snapshot_date - 179) as vehicle_delivered_count_l6m
  from {{ ref('silver_customer_snapshot') }} s
  left join {{ ref('silver_vehicle_ownership') }} h
         on h.customer_id = s.customer_id
        and h.snapshot_date = s.snapshot_date
  group by s.customer_id, s.snapshot_date
)

select
    d.customer_id,
    d.snapshot_date,
    d.days_since_first_completed_txn_days_daily,
    d.days_since_first_completed_txn_days_l12m,
    d.days_since_first_completed_txn_days_l1m,
    d.days_since_first_completed_txn_days_l1w,
    d.days_since_first_completed_txn_days_l2w,
    d.days_since_first_completed_txn_days_l3m,
    d.days_since_first_completed_txn_days_l6m,
    d.days_since_last_completed_txn_days_daily,
    d.days_since_last_completed_txn_days_l12m,
    d.days_since_last_completed_txn_days_l1m,
    d.days_since_last_completed_txn_days_l1w,
    d.days_since_last_completed_txn_days_l2w,
    d.days_since_last_completed_txn_days_l3m,
    d.days_since_last_completed_txn_days_l6m,
    d.txn_accessories_canceled_amount_sum_l1m_vs_l12m,
    d.txn_accessories_canceled_amount_sum_l1m_vs_l3m,
    d.txn_accessories_canceled_amount_sum_l1m_vs_l6m,
    d.txn_accessories_canceled_amount_sum_l3m_vs_l12m,
    d.txn_accessories_canceled_count_l1m_vs_l12m,
    d.txn_accessories_canceled_count_l1m_vs_l3m,
    d.txn_accessories_canceled_count_l1m_vs_l6m,
    d.txn_accessories_canceled_count_l3m_vs_l12m,
    d.txn_accessories_canceled_price_sum_l1m_vs_l12m,
    d.txn_accessories_canceled_price_sum_l1m_vs_l3m,
    d.txn_accessories_canceled_price_sum_l1m_vs_l6m,
    d.txn_accessories_canceled_price_sum_l3m_vs_l12m,
    d.txn_accessories_completed_amount_sum_l1m_vs_l12m,
    d.txn_accessories_completed_amount_sum_l1m_vs_l3m,
    d.txn_accessories_completed_amount_sum_l1m_vs_l6m,
    d.txn_accessories_completed_amount_sum_l3m_vs_l12m,
    d.txn_accessories_completed_count_l12m,
    d.txn_accessories_completed_count_l1m_vs_l12m,
    d.txn_accessories_completed_count_l1m_vs_l3m,
    d.txn_accessories_completed_count_l1m_vs_l6m,
    d.txn_accessories_completed_count_l3m_vs_l12m,
    d.txn_accessories_completed_price_sum_l12m,
    d.txn_accessories_completed_price_sum_l1m_vs_l12m,
    d.txn_accessories_completed_price_sum_l1m_vs_l3m,
    d.txn_accessories_completed_price_sum_l1m_vs_l6m,
    d.txn_accessories_completed_price_sum_l3m_vs_l12m,
    d.txn_canceled_active_day_count_daily,
    d.txn_canceled_active_day_count_l12m,
    d.txn_canceled_active_day_count_l1m,
    d.txn_canceled_active_day_count_l1w,
    d.txn_canceled_active_day_count_l2w,
    d.txn_canceled_active_day_count_l3m,
    d.txn_canceled_active_day_count_l6m,
    d.txn_canceled_amount_sum_daily,
    d.txn_canceled_amount_sum_l12m,
    d.txn_canceled_amount_sum_l1m,
    d.txn_canceled_amount_sum_l1w,
    d.txn_canceled_amount_sum_l2w,
    d.txn_canceled_amount_sum_l3m,
    d.txn_canceled_amount_sum_l6m,
    d.txn_canceled_count_daily,
    d.txn_canceled_count_l12m,
    d.txn_canceled_count_l1m,
    d.txn_canceled_count_l1w,
    d.txn_canceled_count_l2w,
    d.txn_canceled_count_l3m,
    d.txn_canceled_count_l6m,
    d.txn_canceled_price_sum_daily,
    d.txn_canceled_price_sum_l12m,
    d.txn_canceled_price_sum_l1m,
    d.txn_canceled_price_sum_l1w,
    d.txn_canceled_price_sum_l2w,
    d.txn_canceled_price_sum_l3m,
    d.txn_canceled_price_sum_l6m,
    d.txn_canceled_processing_time_max_daily,
    d.txn_canceled_processing_time_max_l12m,
    d.txn_canceled_processing_time_max_l1m,
    d.txn_canceled_processing_time_max_l1w,
    d.txn_canceled_processing_time_max_l2w,
    d.txn_canceled_processing_time_max_l3m,
    d.txn_canceled_processing_time_max_l6m,
    d.txn_canceled_processing_time_min_daily,
    d.txn_canceled_processing_time_min_l12m,
    d.txn_canceled_processing_time_min_l1m,
    d.txn_canceled_processing_time_min_l1w,
    d.txn_canceled_processing_time_min_l2w,
    d.txn_canceled_processing_time_min_l3m,
    d.txn_canceled_processing_time_min_l6m,
    d.txn_completed_active_day_count_daily,
    d.txn_completed_active_day_count_l12m,
    d.txn_completed_active_day_count_l1m,
    d.txn_completed_active_day_count_l1w,
    d.txn_completed_active_day_count_l2w,
    d.txn_completed_active_day_count_l3m,
    d.txn_completed_active_day_count_l6m,
    d.txn_completed_amount_sum_daily,
    d.txn_completed_amount_sum_l12m,
    d.txn_completed_amount_sum_l1m,
    d.txn_completed_amount_sum_l1w,
    d.txn_completed_amount_sum_l2w,
    d.txn_completed_amount_sum_l3m,
    d.txn_completed_amount_sum_l6m,
    d.txn_completed_battery_sum_l12m,
    d.txn_completed_count_daily,
    d.txn_completed_count_l12m,
    d.txn_completed_count_l1m,
    d.txn_completed_count_l1w,
    d.txn_completed_count_l2w,
    d.txn_completed_count_l3m,
    d.txn_completed_count_l6m,
    d.txn_completed_price_sum_daily,
    d.txn_completed_price_sum_l12m,
    d.txn_completed_price_sum_l1m,
    d.txn_completed_price_sum_l1w,
    d.txn_completed_price_sum_l2w,
    d.txn_completed_price_sum_l3m,
    d.txn_completed_price_sum_l6m,
    d.txn_completed_processing_time_max_daily,
    d.txn_completed_processing_time_max_l12m,
    d.txn_completed_processing_time_max_l1m,
    d.txn_completed_processing_time_max_l1w,
    d.txn_completed_processing_time_max_l2w,
    d.txn_completed_processing_time_max_l3m,
    d.txn_completed_processing_time_max_l6m,
    d.txn_completed_processing_time_min_daily,
    d.txn_completed_processing_time_min_l12m,
    d.txn_completed_processing_time_min_l1m,
    d.txn_completed_processing_time_min_l1w,
    d.txn_completed_processing_time_min_l2w,
    d.txn_completed_processing_time_min_l3m,
    d.txn_completed_processing_time_min_l6m,
    d.txn_discount_accessories_completed_count_l12m,
    d.txn_discount_canceled_count_daily,
    d.txn_discount_canceled_count_l12m,
    d.txn_discount_canceled_count_l1m,
    d.txn_discount_canceled_count_l1w,
    d.txn_discount_canceled_count_l2w,
    d.txn_discount_canceled_count_l3m,
    d.txn_discount_canceled_count_l6m,
    d.txn_discount_completed_count_daily,
    d.txn_discount_completed_count_l12m,
    d.txn_discount_completed_count_l1m,
    d.txn_discount_completed_count_l1w,
    d.txn_discount_completed_count_l2w,
    d.txn_discount_completed_count_l3m,
    d.txn_discount_completed_count_l6m,
    d.txn_discount_delivered_count_daily,
    d.txn_discount_delivered_count_l12m,
    d.txn_discount_delivered_count_l1m,
    d.txn_discount_delivered_count_l1w,
    d.txn_discount_delivered_count_l2w,
    d.txn_discount_delivered_count_l3m,
    d.txn_discount_delivered_count_l6m,
    d.txn_discount_nvso_completed_count_l12m,
    d.txn_first_completed_updated_date_min_daily,
    d.txn_first_completed_updated_date_min_l12m,
    d.txn_first_completed_updated_date_min_l1m,
    d.txn_first_completed_updated_date_min_l1w,
    d.txn_first_completed_updated_date_min_l2w,
    d.txn_first_completed_updated_date_min_l3m,
    d.txn_first_completed_updated_date_min_l6m,
    d.txn_last_completed_updated_date_max_daily,
    d.txn_last_completed_updated_date_max_l12m,
    d.txn_last_completed_updated_date_max_l1m,
    d.txn_last_completed_updated_date_max_l1w,
    d.txn_last_completed_updated_date_max_l2w,
    d.txn_last_completed_updated_date_max_l3m,
    d.txn_last_completed_updated_date_max_l6m,
    d.txn_wo_canceled_amount_sum_l1m_vs_l12m,
    d.txn_wo_canceled_amount_sum_l1m_vs_l3m,
    d.txn_wo_canceled_amount_sum_l1m_vs_l6m,
    d.txn_wo_canceled_amount_sum_l3m_vs_l12m,
    d.txn_wo_canceled_count_l1m_vs_l12m,
    d.txn_wo_canceled_count_l1m_vs_l3m,
    d.txn_wo_canceled_count_l1m_vs_l6m,
    d.txn_wo_canceled_count_l3m_vs_l12m,
    d.txn_wo_canceled_price_sum_l1m_vs_l12m,
    d.txn_wo_canceled_price_sum_l1m_vs_l3m,
    d.txn_wo_canceled_price_sum_l1m_vs_l6m,
    d.txn_wo_canceled_price_sum_l3m_vs_l12m,
    d.txn_wo_completed_amount_sum_l1m_vs_l12m,
    d.txn_wo_completed_amount_sum_l1m_vs_l3m,
    d.txn_wo_completed_amount_sum_l1m_vs_l6m,
    d.txn_wo_completed_amount_sum_l3m_vs_l12m,
    d.txn_wo_completed_count_l1m_vs_l12m,
    d.txn_wo_completed_count_l1m_vs_l3m,
    d.txn_wo_completed_count_l1m_vs_l6m,
    d.txn_wo_completed_count_l3m_vs_l12m,
    d.txn_wo_completed_price_sum_l1m_vs_l12m,
    d.txn_wo_completed_price_sum_l1m_vs_l3m,
    d.txn_wo_completed_price_sum_l1m_vs_l6m,
    d.txn_wo_completed_price_sum_l3m_vs_l12m,
    m.first_vehicle_purchase_date,
    m.is_vehicle_buyer,
    m.vehicle_purchase_completed_count_all,
    m.vehicle_purchase_completed_count_l12m,
    m.vehicle_purchase_completed_count_l1m,
    m.vehicle_purchase_completed_count_l3m,
    m.vehicle_purchase_completed_count_l6m,
    o.days_since_last_vehicle_handover,
    o.first_vehicle_handover_date,
    o.is_vehicle_handover_scheduled,
    o.is_vehicle_owner,
    o.vehicle_delivered_count_all,
    o.vehicle_delivered_count_l12m,
    o.vehicle_delivered_count_l1m,
    o.vehicle_delivered_count_l3m,
    o.vehicle_delivered_count_l6m
from don_hang d
join nguoi_mua m on m.customer_id = d.customer_id and m.snapshot_date = d.snapshot_date
join so_huu    o on o.customer_id = d.customer_id and o.snapshot_date = d.snapshot_date
