"""Schema khởi tạo: 4 bảng raw events + bảng features (222 cột, sinh từ feature_spec).

Cột feature được liệt kê LITERAL tại thời điểm viết migration — feature_spec đổi
về sau phải là một migration mới, không sửa file này.

Revision ID: 0001
Revises:
Create Date: 2026-07-23
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# (tên cột, dtype) — "numeric" -> DOUBLE PRECISION, "categorical" -> TEXT
FEATURE_COLUMNS: list[tuple[str, str]] = [
    ("gsm_transaction_completed_txn_count_l1m", "numeric"),
    ("gsm_transaction_completed_txn_count_l3m", "numeric"),
    ("gsm_transaction_completed_txn_count_l6m", "numeric"),
    ("gsm_transaction_completed_txn_count_l12m", "numeric"),
    ("gsm_transaction_completed_txn_count_l1m_vs_l3m", "numeric"),
    ("gsm_transaction_completed_txn_count_l1m_vs_l12m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l1m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l3m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l6m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l12m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l1m_vs_l3m", "numeric"),
    ("gsm_transaction_completed_gmv_sum_l1m_vs_l12m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l1m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l3m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l6m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l12m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l1m_vs_l3m", "numeric"),
    ("gsm_transaction_completed_discount_sum_l1m_vs_l12m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l1m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l3m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l6m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l12m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l1m_vs_l3m", "numeric"),
    ("gsm_transaction_completed_distance_km_sum_l1m_vs_l12m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l1m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l3m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l6m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l12m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l1m_vs_l3m", "numeric"),
    ("vinfast_transaction_completed_txn_count_l1m_vs_l12m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l1m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l3m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l6m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l12m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l1m_vs_l3m", "numeric"),
    ("vinfast_transaction_completed_gmv_sum_l1m_vs_l12m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l1m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l3m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l6m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l12m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l1m_vs_l3m", "numeric"),
    ("vinfast_transaction_completed_discount_sum_l1m_vs_l12m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_gsm_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_gsm_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinfast_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinfast_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinhomes_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinhomes_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinmec_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinmec_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinpearl_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinpearl_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinschool_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinschool_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinclub_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vinclub_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vincomretail_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vincomretail_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_merchant_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_merchant_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vapp_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_vapp_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_fgf_earn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_pts_sum_l1m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_pts_sum_l3m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_pts_sum_l6m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_pts_sum_l12m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_txn_count_l1m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_txn_count_l3m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_txn_count_l6m", "numeric"),
    ("global_loyalty_pnl_fgf_burn_completed_txn_count_l12m", "numeric"),
    ("global_loyalty_primary_earn_pnl_l6m", "categorical"),
    ("global_loyalty_primary_earn_pnl_l12m", "categorical"),
    ("global_loyalty_primary_burn_pnl_l6m", "categorical"),
    ("global_loyalty_primary_burn_pnl_l12m", "categorical"),
]


def _feature_sa_type(dtype: str):
    return sa.Text() if dtype == "categorical" else sa.Float(precision=53)


def upgrade() -> None:
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Integer(), primary_key=True),
        sa.Column("customer_name", sa.Text()),
        sa.Column("phone", sa.Text()),
        sa.Column("email", sa.Text()),
        sa.Column("segment", sa.Text()),
        sa.Column("joined_at", sa.Text()),
    )
    op.create_table(
        "gsm_trips",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("customer_id", sa.Integer(), sa.ForeignKey("customers.customer_id"), nullable=False),
        sa.Column("service_type", sa.Text()),
        sa.Column("original_price", sa.Float(precision=53)),
        sa.Column("discount", sa.Float(precision=53)),
        sa.Column("distance_km", sa.Float(precision=53)),
        sa.Column("status", sa.Text()),
        sa.Column("ts", sa.Text()),
    )
    op.create_table(
        "vinfast_orders",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("customer_id", sa.Integer(), sa.ForeignKey("customers.customer_id"), nullable=False),
        sa.Column("item_type", sa.Text()),
        sa.Column("original_price", sa.Float(precision=53)),
        sa.Column("discount", sa.Float(precision=53)),
        sa.Column("status", sa.Text()),
        sa.Column("processing_hours", sa.Float(precision=53)),
        sa.Column("ts", sa.Text()),
    )
    op.create_table(
        "loyalty_ledger",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("customer_id", sa.Integer(), sa.ForeignKey("customers.customer_id"), nullable=False),
        sa.Column("pnl", sa.Text()),
        sa.Column("direction", sa.Text()),
        sa.Column("points", sa.Integer()),
        sa.Column("status", sa.Text()),
        sa.Column("ts", sa.Text()),
    )
    op.create_index("ix_gsm_trips_customer_id", "gsm_trips", ["customer_id"])
    op.create_index("ix_vinfast_orders_customer_id", "vinfast_orders", ["customer_id"])
    op.create_index("ix_loyalty_ledger_customer_id", "loyalty_ledger", ["customer_id"])

    op.create_table(
        "features",
        sa.Column(
            "customer_id",
            sa.Integer(),
            sa.ForeignKey("customers.customer_id"),
            primary_key=True,
        ),
        *[sa.Column(name, _feature_sa_type(dtype)) for name, dtype in FEATURE_COLUMNS],
    )


def downgrade() -> None:
    op.drop_table("features")
    op.drop_index("ix_loyalty_ledger_customer_id", table_name="loyalty_ledger")
    op.drop_index("ix_vinfast_orders_customer_id", table_name="vinfast_orders")
    op.drop_index("ix_gsm_trips_customer_id", table_name="gsm_trips")
    op.drop_table("loyalty_ledger")
    op.drop_table("vinfast_orders")
    op.drop_table("gsm_trips")
    op.drop_table("customers")
